### PR TITLE
Assembly directly to HYPREMatrix.

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Comment by fredrikekre** [comment]
cc @lijas @termi-official

**Comment by fredrikekre** [comment]
With this you can either assemble every element contribution (might be too slow due to MPI communication, but require less memory):
```julia
A = HYPREMatrix(comm, proc_row_first, proc_row_last)
hypre_assembler = HYPRE.start_assemble!(A)
for cell in cell_for_proc
    ke = ...
    global_dofs_for_cell = ...
    HYPRE.assemble!(hypre_assembler, global_dofs_for_cell, ke)
end
HYPRE.finish_assemble!(hypre_assembler)
```
or assemble the processor-matrix at once:
```julia
A = HYPREMatrix(comm, proc_row_first, proc_row_last)
hypre_assembler = HYPRE.start_assemble!(A)
Alocal = process_local_sparsity_pattern(...)
ferrite_assembler = start_assemble(Alocal)
for cell in cell_for_proc
    ke = ...
    local_dofs_for_cell = ...
    Ferrite.assemble!(ferrite_assembler, local_dofs_for_cell, ke)
end
global_dofs_for_proc = ...
HYPRE.assemble!(hypre_assembler, global_dofs_for_proc, Alocal)
HYPRE.finish_assemble!(hypre_assembler)
```

**Comment by lijas** [comment]
Nice. But would the first example really be that slow? HYPRE_IJMatrixAddToValues does not do any MPI communication right, it is only at assemble_matrix(A.A) where mpi communication is done?

I think I like the first approach better since it more resembles the current assembler in Ferrite and does not require local dof ids

**Comment by fredrikekre** [comment]
Yea you are right, it is actually documented to be

> Not collective

See [`HYPRE_IJMatrixAddToValues`](https://hypre.readthedocs.io/en/latest/api-int-ij.html#_CPPv425HYPRE_IJMatrixAddToValues14HYPRE_IJMatrix9HYPRE_IntP9HYPRE_IntPK12HYPRE_BigIntPK12HYPRE_BigIntPK13HYPRE_Complex).

**Pull request merged**
